### ISSUE TITLE
MethodNotAllowedHttpException in RoutesRequests.php 

### ISSUE THREAD

**Issue by hopewise** [krisanalfa/lumen-jwt#1]
Hello @krisanalfa 

I've reviewed the app.php, so, there were so many missing bootstrapping, thanks for the great work!

I could pass a token, and jwt.auth has worked, however, I got error when tried to `/auth/login`

```
MethodNotAllowedHttpException in RoutesRequests.php line 445:
in RoutesRequests.php line 445
at Application->handleDispatcherResponse(array('2', array('POST'))) in RoutesRequests.php line 381
at Application->Laravel\Lumen\Concerns\{closure}() in RoutesRequests.php line 624
at Application->sendThroughPipeline(array(), object(Closure)) in RoutesRequests.php line 382
at Application->dispatch(null) in RoutesRequests.php line 327
at Application->run() in index.php line 28

```

Mainly I will be using lumen for APIs, so I will not be logging into it, however its curiosity to know why its not working.. I think I have to dig more in the lumen& laravel architecture, do you know good resources links?

**Comment by krisanalfa** [comment]
Hi @hopewise. Which HTTP method did you use when you try to request a token? I used `POST` request. And it works fine.

``` sh
curl -X "POST" "http://mylumenapp.local.dev/auth/login" \
     -H "Content-Type: application/x-www-form-urlencoded" \
     --data-urlencode "email=johndoe@example.com" \
     --data-urlencode "password=johndoe"
```

![Nice response](https://cloud.githubusercontent.com/assets/3734729/13633808/f8b5123a-e623-11e5-89d5-6d637dd9ca56.png)

Here's some good resource you may start with:
- https://laravelista.com
- https://laravel-news.com/blog/
- https://murze.be
- https://laraveltips.wordpress.com
- https://laracasts.com

**Comment by hopewise** [comment]
Ah, OK, I used GET..
Thanks allot for the links..

**Comment by krisanalfa** [comment]
You're very welcome sir.
