### ISSUE TITLE
Integrate Dingo with CORS Support

### ISSUE THREAD

**Issue by YasirAmeen** [krisanalfa/lumen-jwt#10]
Can you add Dingo and Cors with it to make it complete package,

**Comment by krisanalfa** [comment]
Hi, Sir. Thank for using this. Actually I've been thinking about it too. I'll make a roadmap for future release.

**Comment by krisanalfa** [comment]
Fixed at [5.3.7](https://github.com/krisanalfa/lumen-jwt/tree/5.3.7) release.
