### ISSUE TITLE
I am facing following error when updatin composer (I am new to PHP :-) )

### ISSUE THREAD

**Issue by YasirAmeen** [krisanalfa/lumen-jwt#12]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package illuminate/routiminate/hashingng could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package illu could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by YasirAmeen** [comment]
Even I am not able to install any external package

**Comment by krisanalfa** [comment]
Could you share your `package.json` file?

**Comment by YasirAmeen** [comment]
Here is the composer json file,

I did not change any thing in it, i just download your repository and the following content is from your project.

```json
{
    "name": "newLife",
    "description": "The Laravel Lumen Framework.",
    "keywords": ["framework", "laravel", "lumen"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/lumen-framework": "^5.3",
        "vlucas/phpdotenv": "~2.2",
        "illu": "^5.3",
        "tymon/jwt-auth": "0.5.*",
        "illuminate/cookie": "^5.3",
        "flipbox/lumen-generator": "^5.3"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "phpunit/phpunit": "~4.0",
        "symfony/var-dumper": "^3.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "files": [
            "app/helpers.php"
        ]
    },
    "autoload-dev": {
        "classmap": [
            "tests/",
            "database/"
        ]
    }
}
```

**Comment by YasirAmeen** [comment]
`{
    "name": "newLife",
    "description": "The Laravel Lumen Framework.",
    "keywords": ["framework", "laravel", "lumen"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/lumen-framework": "^5.3",
        "vlucas/phpdotenv": "~2.2",
        "illu": "^5.3",
        "tymon/jwt-auth": "0.5.*",
        "illuminate/cookie": "^5.3",
        "flipbox/lumen-generator": "^5.3"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "phpunit/phpunit": "~4.0",
        "symfony/var-dumper": "^3.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "files": [
            "app/helpers.php"
        ]
    },
    "autoload-dev": {
        "classmap": [
            "tests/",
            "database/"
        ]
    }
}
`

**Comment by krisanalfa** [comment]
Seems good. How do you install the package? Do you have a poor internet connection?

**Comment by YasirAmeen** [comment]
i just reinstall and it fixed, working now , Now you my close this issue as solve. 
Thanks

**Comment by YasirAmeen** [comment]
But Request Please And Dingo with as early as possible :-)

**Comment by krisanalfa** [comment]
Granted! See [0689f72b0b5bc41520f4417754bef4837f6b586e](https://github.com/krisanalfa/lumen-jwt/commit/0689f72b0b5bc41520f4417754bef4837f6b586e). Install with [v5.3.7](https://github.com/krisanalfa/lumen-jwt/tree/5.3.7). You're very lucky, I released this version just a moment ago! And by the way, thanks for using this.
