### ISSUE TITLE
{"message":"not_found"} after following quick start

### ISSUE THREAD

**Issue by smarques84** [krisanalfa/lumen-jwt#13]
I just tried your started kit and followed every step but after i run:

`curl -X POST -F "email=johndoword=johndoe" "http://localhost:8001/auth/login"`

I always get:
`{"message":"not_found"}`

Did i miss something?

**Comment by cleitonsouza** [comment]
Maybe `php artisan migrate --seed` ?

**Comment by smarques84** [comment]
I already ran that command and checked if the database has the the user and its inserted correctly.

**Comment by cleitonsouza** [comment]
Test with `api/auth/login`.

Try setting `API_PREFIX` in your env file.

**Comment by krisanalfa** [comment]
Thanks to @cleitonsouza. I'm sure it's all about your Dingo configuration. Change your `.env` file. Change `API_PREFIX` to something like this:

```
API_PREFIX=api
```

Maybe I'm missing documentation for this info. Can someone send me a PR?

**Comment by casperwitting** [comment]
I've had this issue also, fixed it by adding /api in the url: 

`http://localhost:8001/api/auth/login`

@krisanalfa please update the readme with this

**Comment by krisanalfa** [comment]
@casperwitting Ok, can you send me a PR to update current readme? I'm lil busy right now.

**Comment by smarques84** [comment]
Can confirm to make it work you need to add the /api to the url like @casperwitting said, just setting 
`API_PREFIX=api` in the `.env` file is not enough
