### ISSUE TITLE
not overriding config/auth.php 

### ISSUE THREAD

**Issue by Haafiz** [krisanalfa/lumen-jwt#18]
If I override auth.php in config directory of lumen installation, then this;

```php
    'providers' => [
        'jwt' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],
    ],
```

is still coming from package's config/auth.php file.

**Comment by krisanalfa** [comment]
Hi, firstly I want to thank you for reporting this issue. I'll investigate this issue tomorrow, because I'm on vacation today. Sorry for inconvenience.

**Comment by krisanalfa** [comment]
Hi, you can fix this issue with below step:

- After registering

```php
$app->register(Zeek\LumenDingoAdapter\Providers\LumenDingoAdapterServiceProvider::class);
```

in your `bootstrap/app.php` file, add this line:

```php
$app->configure('auth');
```

**Comment by Haafiz** [comment]
Thanks for response  but I tried this and it didn't work.

**Comment by krisanalfa** [comment]
You can simply `composer update` on your project to fix this issue. Thanks.
