### ISSUE TITLE
MethodNotAllowedHttpException in RoutesRequests.php line 598

### ISSUE THREAD

**Issue by ChaimaeELL** [krisanalfa/lumen-jwt#19]
i tray to route a route using my access-token but i got this exception 
Lumen 5.3
OAuth2

thanks you

**Comment by krisanalfa** [comment]
Which path you're accessing? Could you send a cURL command to reproduce this issue?

**Comment by ChaimaeELL** [comment]
```php
$app->post('/oauth/token/refresh',['middleware' => 'auth','namespace' => 'Laravel\Passport\Http\Controllers', 'uses' => 'TransientTokenController@refresh']);
```

- that what i tried to access to in my web.php

**Comment by krisanalfa** [comment]
How did you access that URL?

**Comment by ChaimaeELL** [comment]
i used postman to access to this url : http://localhost/OAuth/public/oauth/token/refresh with post method

**Comment by krisanalfa** [comment]
I understand. But which HTTP method?

**Comment by ChaimaeELL** [comment]
post method

**Comment by ghost** [comment]
I think GET will work instead of POST, if you are using POST method you need to create a form with POST method in the view

**Comment by krisanalfa** [comment]
Refresh token accept `PATCH` method. Not `POST`. Try using `PATCH` and see if the problem still occurred.
