### ISSUE TITLE
When token match return 'memcached' not found

### ISSUE THREAD

**Issue by andikayopr** [krisanalfa/lumen-jwt#2]
When trying to authenticate:

localhost/lumen_jwt/public/index.php?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6Imh0dHA6XC9cL2xvY2FsaG9zdFwvbHVtZW5fand0XC9wdWJsaWNcL2F1dGhcL2xvZ2luIiwiaWF0IjoxNDU3ODgxMjIwLCJleHAiOjE0NTc4ODQ4MjAsIm5iZiI6MTQ1Nzg4MTIyMCwianRpIjoiODdmZWZjMTllMjE5NDE4ODQ1MzMyMzdjM2Q0Y2ZmN2YifQ.APXdnsMgMrlxgnGNbxnbPoboKPKpNmmS6Ta-MPwrehY
## Got this error :

<br />
<b>Fatal error</b>:  Class 'Memcached' not found in 
<b>/opt/lampp/htdocs/lumen_jwt/vendor/illuminate/cache/MemcachedConnector.php</b> on line 
<b>51</b>
<br />
<br />
<b>Fatal error</b>:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file &quot;/opt/lampp/htdocs/lumen_jwt/storage/logs/lumen.log&quot; could not be opened: failed to open stream: Permission denied' in /opt/lampp/htdocs/lumen_jwt/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:87
Stack trace:
#0 /opt/lampp/htdocs/lumen_jwt/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\StreamHandler-&gt;write(Array)
#1 /opt/lampp/htdocs/lumen_jwt/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler-&gt;handle(Array)
#2 /opt/lampp/htdocs/lumen_jwt/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger-&gt;addRecord(400, Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#3 /opt/lampp/htdocs/lumen_jwt/vendor/laravel/lumen-framework/src/Exceptions/Handler.php(36): Monolog\Logger-&gt;error(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#4 /opt/lampp/htdocs/lumen_jwt/app/Exceptions/Handler.php(36): La in

<b>/opt/lampp/htdocs/lumen_jwt/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php</b> on line 
<b>87</b>
<br />

---

Hehe. Lol. It happens because i'm new to laravel/lumen.

solution :
Change the cache driver in .env from memcached to file.

CACHE_DRIVER=file

Big thanks for @krisanalfa it's really works and help me a lot.
Also greetings from bekasi.

**Comment by krisanalfa** [comment]
Straight ahead man, I love you!
