### ISSUE TITLE
InvalidArgumentException in AuthManager.php line 102: Auth guard driver [api] is not defined.

### ISSUE THREAD

**Issue by ChaimaeELL** [krisanalfa/lumen-jwt#21]
the api's driver is not defined i don't no way, please someone help me

**Comment by ghost** [comment]
Need to add AuthManager class in app.php, which is present in illuminate/cache folder.

**Comment by ChaimaeELL** [comment]
why i shoud add AuthManager class in app.php. Thanks to you

**Comment by ghost** [comment]
Thanks,
I told you just try it if the issue may go away, its not permanent its temporary

**Comment by ChaimaeELL** [comment]
ah ok thanks i will try it and tell you what happened ^_^
