### ISSUE TITLE
Command route:list doesn't work

### ISSUE THREAD

**Issue by seuaCoder** [krisanalfa/lumen-jwt#22]
On a fresh install of this package, the command :

php artisan route:list 

does not list the routes, the routes are empty.

Any solution ?

**Comment by vrubiella** [comment]
lumen not include this command, you can added with external package, for example https://packagist.org/packages/thedevsaddam/lumen-route-list

**Comment by Zyles** [comment]
I have the same problem. The package is installed.

The routes list is empty.

**Comment by krisanalfa** [comment]
There's problem in [this](https://github.com/appzcoder/lumen-route-list) package. I'll contact the developer soon.

**Comment by krisanalfa** [comment]
Please update `lumen-generator` to version `5.4.*` to resolve this issue. Sorry for inconvenience.
