### ISSUE TITLE
Package for CORS

### ISSUE THREAD

**Issue by isometriq** [krisanalfa/lumen-jwt#24]
Not an issue, just to indicate that maybe this package would fit well in the bundle
https://github.com/barryvdh/laravel-cors

**Comment by krisanalfa** [comment]
Thanks for your advice! Actually I made this package as simple as possible. The CORS itself is not the main focus on this boilerplate, so I made a simple Provider. If you want to change to @barryvdh's, it's all yours, but for now I'm keeping this Provider.
