### ISSUE TITLE
[PHP 5.6] Getting 'invalid_credentials' on production, while it works on local machine.

### ISSUE THREAD

**Issue by naneri** [krisanalfa/lumen-jwt#29]
I have pushed the code to a linux machine and it always throws this error 'invalid_credentials'. (I did seed the database correctly. )

**Comment by krisanalfa** [comment]
What's the HTTP Status Code it returned? Have you tried using the same `composer.lock` file from your local machine in your production machine? Do you have any steps to reproduce this issue?

**Comment by naneri** [comment]
I do use the same composer lock. The only change that I have made is that I had my own database, and did not use the migrations. I imported my MySQL dump to my machine and the app worked right away. But it did not on production. On my local machine I have Windows 7 and on production there is Linux

**Comment by naneri** [comment]
There were zero changes to the code. Only .env file.

**Comment by krisanalfa** [comment]
Double check your request. Since I cannot reproduce the issue (I don't have any windows server), it's pretty hard to figure out what's wrong. I guess this issue raised because of specific environment. Oh, what's HTTP status code returned? Is it `400` or `401`?

**Comment by naneri** [comment]
I used CURL to send requests. It returns {"message":"invalid_credentials"} 
I tried to dump request params directly and they are correct.

**Comment by naneri** [comment]
I get 401

**Comment by naneri** [comment]
I have tried to deploy to another Linux remote server and it worked fine. There should be something to do with that machine PHP setup.

**Comment by naneri** [comment]
@krisanalfa I have tried sshing to the machine and run artisan tinker to check if Aith::once($credentials) works. It worked correctly under tinker :/

**Comment by naneri** [comment]
Could that be somehow related that there is PHP 5.6 on the server (And I have used PHP 7 on other machines). 
By the way the problem lies in the illuminate\auth\EloquentUserProvider.php 
:93  public function retrieveByCredentials(array $credentials)

I don't know why, but this method does not find a User even though he exists (I have tried searching using php artisan tinker and there were no problems with that).

**Comment by gstrobl** [comment]
I have the same problem.

**Comment by krisanalfa** [comment]
Hi @naneri, what's exact PHP version on your production server? Mine is 5.6.30 and it's working. Please make sure your PHP version is above 5.6.4 as per documented [here](https://lumen.laravel.com/docs/5.4).

**Comment by naneri** [comment]
@krisanalfa I have found out - that is directly related to Amazon Aurora database. When switching engine to MySQL engine it works correctly.  

What is really really awkward is that running query User::where('email', 'new@email.com')->first() from artisan console - it works correctly, but when running the code in EloquentUserProvider.php it does not return the user. So that is nothing to do with the package - I will post more info on the question in Laravel repository.

**Comment by gstrobl** [comment]
@krisanalfa I am working on my local machine with xampp(Apache/2.4.25 (Win32) OpenSSL/1.0.2j PHP/7.0.15) and I get a 401 Error. Should I try the homestead vagrent box?

**Comment by krisanalfa** [comment]
@gstrobl are you sure you have seeded your database, Sir?

**Comment by gstrobl** [comment]
@krisanalfa Yes. The post-request api/auth/login?email=johndoe@example.com&password=johndoe works.

**Comment by krisanalfa** [comment]
@gstrobl so is it working now?

**Comment by gstrobl** [comment]
@krisanalfa No, I always get an 401 error.
