### ISSUE TITLE
The token is still valid after having generated a new one

### ISSUE THREAD

**Issue by dnsdirmx** [krisanalfa/lumen-jwt#3]
Hi I have a question, as I can change where I store the token.
to test the previous token is still valid , if more than one application command to start validating previous session tokens.
Excuse my English

**Comment by krisanalfa** [comment]
Hi, I reproduced the issue, but everything works fine. Could you tell me how to reproduce this bugs?

**Comment by krisanalfa** [comment]
Actually this is not a bug. You should invalidate the old token to make old token become invalid.
