### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by seuaCoder** [krisanalfa/lumen-jwt#31]
Hi,

My project was working perfectly on my local server but not when i make it online.

I can login successfully but after that, each request receive  a 401 error like the token is not right but it is there and it's right.  I tried to run a local server on my server and send some curl request locally it is working.

What could be the problem ? 

Thank you.

**Comment by seuaCoder** [comment]
It is not duplicate, i checked all the workaround here, doesn't work ... I added what needed in the .htaccess file.

**Comment by krisanalfa** [comment]
What webserver are you using? Can you do this:

- Inside your server, execute `php artisan serve --host=0.0.0.0`
- Access your application remotely

Is it still throw `401` error?

**Comment by seuaCoder** [comment]
I'm using Apache. yes with the php server it is working. 

I was not able to fix this but i switched to PHP-FPM and it's working now. Apache probable stripped the Authorization header. Even if the .htaccess fix was there.

**Comment by krisanalfa** [comment]
Do you have `mod_rewrite` enabled in your Apache configuration?

**Comment by seuaCoder** [comment]
yes it is enabled

**Comment by krisanalfa** [comment]
Strange. I can't investigate this issue, since it very rely on each machine. Try dumping `$_SERVER` and `getallheaders` value. If `Authorization` header is still absent, then the problem should be on the webserver, not your application.

**Comment by seuaCoder** [comment]
Yes i'm almost sure that it's server configuration because moving to php-fpm fixed the problem.
