### ISSUE TITLE
How to refresh token?

### ISSUE THREAD

**Issue by pmventura** [krisanalfa/lumen-jwt#33]
@krisanalfa I tried access to access api/auth/refresh from Postman collection you provided. But it says "Token has expired". Do I still need to configure something?

**Comment by krisanalfa** [comment]
Could you please copy-paste your cURL request + response here?

**Comment by pmventura** [comment]
Here it is man @krisanalfa 

<img width="844" alt="screen shot 2017-05-31 at 3 46 06 pm" src="https://cloud.githubusercontent.com/assets/4361782/26621165/5a05f4fa-4618-11e7-82ab-79b3b3ee0e4b.png">

**Comment by krisanalfa** [comment]
Have you done any authentication request before accessing refresh endpoint?

**Comment by pmventura** [comment]
@krisanalfa Yes. Else, i will be receiving different error if not authenticated right?

I've tried to take out this route outside the middleware and it works fine. But will it be the best practice?

$api->patch('/auth/refresh', [
            'uses' => 'App\Http\Controllers\Auth\AuthController@patchRefresh',
            'as' => 'api.auth.refresh']);

**Comment by krisanalfa** [comment]
No. You should use `auth` middleware for _refresh_ endpoint. Because any refreshed token should be a valid token, it represents a single session for a user. Mine is working here.

After you logged in, can you access `/api/auth/user` endpoint?

**Comment by pmventura** [comment]
Yeah, all endpoints are working fine so long as token still valid. But the moment it expired, I can't able to refresh the token.

**Comment by pmventura** [comment]
Let me know if you want the steps to reproduce this

**Comment by pmventura** [comment]
@krisanalfa does the refresh endpoint is working on your end when you pass an expired token?

**Comment by krisanalfa** [comment]
No. Refreshed token should be a valid token. Which is expired token would be rejected.

**Comment by pmventura** [comment]
Hmm, i see. But I believe you don't want the user to re-authenticate(bring back to login) if the token expired right? Should just refresh and you'll get a new access token.

**Comment by krisanalfa** [comment]
Yeah, you need to re-login before refreshing the token (only if you got token expired).
