### ISSUE TITLE
config/jwt.php not working

### ISSUE THREAD

**Issue by skormel** [krisanalfa/lumen-jwt#8]
Hi @krisanalfa,

First I congrantulate you for the great work, this project save me a lots of time.

I've modified ttl property with value of 1 (1 minute to expiration) in config/jwt.php, but jwt generated continue with default value (60 minutes).

How can I solve this issue?

Thanks for all.

**Comment by krisanalfa** [comment]
Hi @skormel, sorry for late response. I was on vacation. Anyway, thank you and I'm happy that can help you. So, here's the deal: There's missing method I need to call before `JWTAuthServiceProvider` registered, and I forgot to add that line. So, here's a quick fix for you. Just before this line (on `app/bootstrap.php`):

``` php
$app->register(Tymon\JWTAuth\Providers\JWTAuthServiceProvider::class);
```

Add:

``` php
$app->configure('jwt');
$app->register(Tymon\JWTAuth\Providers\JWTAuthServiceProvider::class);
```

If you mind, you can send me a pull request to `develop` branch. I will publish it once I'm on office.

**Comment by krisanalfa** [comment]
Resolved by a merge `8467899..aa91033`

**Comment by skormel** [comment]
I see that you've already fixed the error.

Thanks you very much,

**Comment by krisanalfa** [comment]
No problem, Sir. Glad to help you.
