### ISSUE TITLE
error: token_invalid

### ISSUE THREAD

**Issue by j-quelly** [krisanalfa/lumen-jwt#9]
Using Postman I authenticate John Doe:

http://websiteprogress.ca/uploads/20161025191157444.png

That works fine, but when I try to check the authenticated user by passing the token as a parameter:

http://websiteprogress.ca/uploads/20161025191453612.png

or via the header:

http://websiteprogress.ca/uploads/20161025191416698.png

I get an error: token_invalid.  

Am I do something wrong?

**Comment by krisanalfa** [comment]
Hi, first thing, how did you run the app? Is it via PHP built in server or anything else? Secondly, have you set your `JWT_SECRET`?

**Comment by krisanalfa** [comment]
I cannot reproduce your issue. But here's a list you may check:
- Set your `JWT_SECRET` in your `.env`
- Try to restart your web server after you changed your `JWT_SECRET`
- Make sure you have copied all of your `token` into your `Authorization` header (sometimes I miss one character or so in my `token` and then the `token_invalid` exception raised)

**Comment by j-quelly** [comment]
Ahh yes, it seems I wrote JWT_TOKEN in my .env file instead of JWT_SECRET.  oops!

Thank you for the help and great work by the way :)

**Comment by krisanalfa** [comment]
@studio174 glad to help you, sir
